name: Tesouro Direto

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install requests

      - name: Executar scraper
        run: |
          python ./scraper.py

      - name: Commit JSON seguro
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # garante que estamos na branch atual
          git checkout main

          # adiciona arquivo sempre
          git add taxa.json

          # DEBUG: mostra diferença real
          echo "=== DIFF ==="
          git diff --cached || true

          # força commit apenas se necessário
          git commit -m "Atualiza taxa" || echo "Nada para commitar"

          git push origin main
