name: Tesouro Direto

on:
  workflow_dispatch:

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Mostrar estrutura
        run: |
          pwd
          ls -R

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Testar scraper
        run: |
          python ./scraper.py
