name: Tesouro Direto

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install requests

      - name: Executar scraper
        run: |
          python ./scraper.py

      - name: Commit JSON (seguro contra conflito)
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # garante estado atualizado sem conflito de merge
          git fetch origin main

          git checkout main
          git reset --hard origin/main

          # executa alteração
          git add taxa.json

          git diff --cached --quiet && echo "Nada mudou" && exit 0

          git commit -m "Atualiza taxa"

          git push origin main
